version: '3.8'

services:
  pdf-processor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-processor-app
    volumes:
      - ./web-build:/app/web-build
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  nginx:
    image: nginx:stable-alpine
    container_name: pdf-processor-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pdf-processor-app
    restart: unless-stopped
