version: '3.8'

services:
  pdf-processor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-processor-app
    volumes:
      - ./web-build:/app/web-build
    ports:
      - "9091:9091"  # ✅ Map host:container correctly
    environment:
      - NODE_ENV=production
    restart: unless-stopped
